### ISSUE TITLE
Are these DDR training API codes not open source?

### ISSUE THREAD

**Issue by Grubby0624** [open-power/ocmb-explorer-fw#1]
https://github.com/open-power/ocmb-explorer-fw/blob/33e3301f619163c8d3aad373b045cb8db494d3d1/_exp/release_lib/inc/ddr_api.h#L121

Are these DDR training API codes not open source? I want to know what role the input parameters of this function play in the DDR training process. If I am paired with RDIMM, are these parameters necessary? Thank you

**Comment by 28varada** [comment]
The user_input_msdg_t structure with comments is defined in the file ddrphy_toolbox.h.

**Comment by Grubby0624** [comment]
OK I got it ,thanks!
