### ISSUE TITLE
Are these parameters related to DIMM type?

### ISSUE THREAD

**Issue by Grubby0624** [open-power/ocmb-explorer-fw#2]
https://github.com/open-power/ocmb-explorer-fw/blob/33e3301f619163c8d3aad373b045cb8db494d3d1/_exp/release_lib/inc/ddrphy_toolbox.h#L346

Excuse me: Does something like ATxImpedance/ATxSlewRate/CKTxImpedance/CKTxSlewRate refer to the impedance/slew rate of the Memory Controller side? Does it have anything to do with the type of DIMM the motherboard is paired with?

**Comment by dcrowell77** [comment]
You can see some usage of the parameter in the hostboot code here in case that helps - https://github.com/open-power/hostboot/search?q=ATxImpedance

@esteban012 fyi

**Comment by sglancy6** [comment]
@Grubby0624 

The ATxImpedance refers to the address line drive impedance from the memory controller.
The ATxSlewRate refers to the address line slew rates from the memory controller.
The CKTxImpedance refers to the clock drive impedance from the memory controller.
The CKTxSlewRate  refers to the clock slew rate from the memory controller.

As these are signal integrity related settings, they depend upon the memory card and memory configurations being used.

**Comment by Grubby0624** [comment]
Ok, I see. Thank you so much
